### ISSUE TITLE
Error on Running The Server Locally

### ISSUE THREAD

**Issue by phoenixml** [microsoft/MHA#875]
Hi All, 
I am trying to run the server locally on ubuntu I install nmp and nodejs latest releases and run the blow command and getting this error any idea why? 

npm run dev-server

> mha@1.0.0 dev-server
> webpack serve --mode development

[webpack-cli] Failed to load '/home/ml/Downloads/MHA-main/webpack.config.js' config
[webpack-cli] /home/user/Downloads/MHA-main/node_modules/cosmiconfig/dist/index.js:78
    if (metaConfig.config?.loaders) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.patchedRequire [as require] (/home/ml/Downloads/MHA-main/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ml/Downloads/MHA-main/node_modules/fork-ts-checker-webpack-plugin/lib/plugin.js:27:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

Appreciated your help in advance, thank you :)

**Comment by stephenegriffin** [comment]
likely not relevent anymore
